---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# morsecode

<!-- badges: start -->
<!-- badges: end -->

This package converts text into Morse code, in various formats suitable for graphing and making art. You probably don't need this.

## Installation

You can install morsecode with:

``` r
remotes::install_github("xmarquez/morsecode")
```

## Basic usage

The basic functions all use text_to_*:

```{r example}
library(morsecode)
text <- "Hello I am a text"

text_to_morse_chars(text)
```

You can also turn text into binary Morse code:

```{r}

text_to_morse_numeric(text)
```

Or a data frame, suitable for graphing:

```{r}
library(dplyr)
library(ggplot2)

df <- text_to_morse_segments(text, line_length = 10)

df %>%
  ggplot(aes(x = x, xend = xend, y = y, yend = yend,
             color = sample(group))) +
  geom_segment(size = 3, show.legend = FALSE) +
  theme_void() +
  scale_color_viridis_c()
```

Or even sound:

```{r, eval=FALSE}

sound <- text_to_morse_sounds(text, pulse_duration = 0.05,
                              play = FALSE)

audio::play(sound, rate = 8000)
```

